#!/usr/bin/env bash
# write script to Installs iginx server
sudo apt-get update
sudo apt-get -y install nginx
sudo rm -r /var/www/html/*
sudo echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
